export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const INIT_INGREDIENTS = "INIT_INGREDIENTS";
export const INIT_INGREDIENTS_FAILED = "INIT_INGREDIENTS_FAILED";

export const ORDER_INIT = "ORDER_INIT";
export const ORDER_BURGER_START = "ORDER_BURGER_START";
export const ORDER_BURGER_SUCCESS = "ORDER_BURGER_SUCCESS";
export const ORDER_BURGER_FAIL = "ORDER_BURGER_FAIL";
